### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by sonyco-4u**
In this Project I did the following
1. update style.css
2. update index.html
3. use animation property.

### CODE REVIEW

**Review by leonardodiasb — COMMENTED** [review]
# INVALID ❌ ❌ ❌ 

Hi @, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - You submitted a merged PR. Please open a new Pull Request from the correct branch of this project and re-submit again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

**Comment by sonyco-4u** [comment]
@leonardodiasb do I have to create a new branch and name it Deployment

**Comment by sonyco-4u** [comment]
https://github.com/sonyco-4u/Portfolio-microverse2/pull/10

**Comment by sonyco-4u** [comment]
@leonardodiasb please can I submit this 
https://github.com/sonyco-4u/Portfolio-microverse2/pull/10

**Pull request merged**
